# Generated by Django 3.2.2 on 2021-05-20 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0011_auto_20210520_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='insta_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
