# Generated by Django 3.2.2 on 2021-05-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_alter_image_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.png', upload_to='profile_pics/'),
        ),
    ]
