# Generated by Django 3.2.2 on 2021-05-20 12:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0016_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
